not install composer on deploy

diff --git a/scripts/deploy b/scripts/deploy
--- a/scripts/deploy
+++ b/scripts/deploy
@@ -82,11 +82,11 @@ read -p "origin/" BRANCH
 echo "Switching to branch"
 git checkout ${BRANCH} || { echo "Unable to checkout branch."; exit 1; }
 
-if [[ -f "composer.json" ]];
-then
-	echo "Installing composer packages"
-	composer install --no-dev || { echo "Unable to install composer packages."; exit 1; }
-fi
+# if [[ -f "composer.json" ]];
+# then
+# 	echo "Installing composer packages"
+# 	composer install --no-dev || { echo "Unable to install composer packages."; exit 1; }
+# fi
 
 if [[ -f "package.json" ]];
 then
