move svn deploy script to scripts folder

diff --git a/scripts/deploy b/scripts/deploy
--- a/scripts/deploy
+++ b/scripts/deploy
@@ -21,11 +21,8 @@
 # The slug of your WordPress.org plugin
 WP_PLUGIN_SLUG="woo-better-shipping-calculator-for-brazil"
 
-# GITHUB user who owns the repo
-GITHUB_REPO_OWNER="luizbills"
-
 # GITHUB Repository name
-GITHUB_REPO_NAME="wc-better-shipping-calculator-for-brazil"
+GITHUB_REPO_SLUG="luizbills/wc-better-shipping-calculator-for-brazil"
 
 # folder with plugin banner and screenshots
 # note: you should commit these assets separately
@@ -34,7 +31,7 @@ PLUGIN_ASSETS_DIR=".wordpress-org"
 # ----- STOP EDITING HERE -----
 
 set -e
-clear
+clear >$( tty ) # clear the terminal
 
 # ASK INFO
 echo "--------------------------------------------"
@@ -55,31 +52,26 @@ read -p "PRESS [ENTER] TO BEGIN RELEASING "${VERSION}
 clear
 
 # VARS
-ROOT_PATH=$(pwd)"/"
-TEMP_GITHUB_REPO=${WP_PLUGIN_SLUG}"-git"
-TEMP_SVN_REPO=${WP_PLUGIN_SLUG}"-svn"
+CURRENT_DIR="."
+DIR="$( realpath ${CURRENT_DIR} )"
+TEMP_GITHUB_REPO="/tmp/${WP_PLUGIN_SLUG}-git"
+TEMP_SVN_REPO="/tmp/${WP_PLUGIN_SLUG}-svn"
 SVN_REPO="http://plugins.svn.wordpress.org/${WP_PLUGIN_SLUG}/"
-GIT_REPO="https://github.com/${GITHUB_REPO_OWNER}/${GITHUB_REPO_NAME}"
+GIT_REPO="https://github.com/${GITHUB_REPO_SLUG}.git"
 
 # DELETE OLD TEMP DIRS
-rm -Rf $ROOT_PATH$TEMP_GITHUB_REPO
-
-# CHECKOUT SVN DIR IF NOT EXISTS
-if [[ ! -d $TEMP_SVN_REPO ]];
-then
-	echo "Checking out WordPress.org plugin repository"
-	svn checkout $SVN_REPO $TEMP_SVN_REPO || { echo "Unable to checkout repo."; exit 1; }
-fi
+rm -Rf $TEMP_GITHUB_REPO
+rm -rf $TEMP_SVN_REPO
 
 # CLONE GIT DIR
 echo "Cloning GIT repository from GITHUB"
 git clone --progress --recurse-submodules $GIT_REPO $TEMP_GITHUB_REPO || { echo "Unable to clone repo."; exit 1; }
 
 # MOVE INTO GIT DIR
-cd "$ROOT_PATH$TEMP_GITHUB_REPO"
+cd "$TEMP_GITHUB_REPO"
 
 # LIST BRANCHES
-clear
+# clear
 git fetch origin
 echo "WHICH BRANCH DO YOU WISH TO DEPLOY?"
 git branch -r || { echo "Unable to list branches."; exit 1; }
@@ -96,20 +88,37 @@ then
 	composer install --no-dev || { echo "Unable to install composer packages."; exit 1; }
 fi
 
-echo ""
-read -p "PRESS [ENTER] TO DEPLOY BRANCH "${BRANCH}
+if [[ -f "package.json" ]];
+then
+	echo "Installing composer packages"
+	npm install || { echo "Unable to install npm packages."; exit 1; }
+fi
+
+echo "Looking for PHP syntax errors"
+find . -type f -name '*.php' ! -path './vendor/*' -print0 | while read -d $'\0' file
+do
+	output=$(php -l "$file")
+	if [ ! $? -eq 0 ];
+	then
+		echo -e "\e[31mPHP Syntax Error!\e[0m"
+		exit 1
+	fi
+done
+echo "No syntax errors found"
 
 # REMOVE UNWANTED FILES & FOLDERS
 echo "Removing unwanted files"
 rm -Rf .git
 rm -Rf .github
 rm -Rf tests
+rm -Rf docs
+rm -Rf scripts
+rm -Rf node_modules
 rm -f .gitattributes
 rm -f .gitignore
 rm -f .gitmodules
 rm -f .travis.yml
-rm -f package.json
-rm -f composer.json
+rm -f package-lock.json
 rm -f composer.lock
 rm -f phpunit.xml
 rm -f phpunit.xml.dist
@@ -117,19 +126,19 @@ rm -f README.md
 rm -f .coveralls.yml
 rm -f .editorconfig
 rm -f CONTRIBUTING.md
-rm -f "${0}" # don't deploy this file
-rm -f .init.sh
-rm -f .gitpod.yml
 rm -f .gitpod.dockerfile
+rm -f .gitpod.yml
+rm -f .prettierrc.json
 
-# don't deploy WordPress plugin banners and icons
-if [[ -n PLUGIN_ASSETS_DIR ]];
-then
-    rm -Rf ${PLUGIN_ASSETS_DIR}
-fi
+echo ""
+read -p "PRESS [ENTER] TO DEPLOY BRANCH "${BRANCH}
+
+# CHECKOUT SVN DIR IF NOT EXISTS
+echo "Checking out WordPress.org plugin SVN repository"
+svn checkout $SVN_REPO $TEMP_SVN_REPO || { echo "Unable to checkout repo."; exit 1; }
 
 # MOVE INTO SVN DIR
-cd "$ROOT_PATH$TEMP_SVN_REPO"
+cd "$TEMP_SVN_REPO"
 
 # UPDATE SVN
 echo "Updating SVN"
@@ -139,11 +148,18 @@ svn update || { echo "Unable to update SVN."; exit 1; }
 echo "Replacing trunk"
 rm -Rf trunk/
 
+# COPY GIT DIR TO TRUNK
+cp -a "${TEMP_GITHUB_REPO}/." trunk/
+
+if [[ -d "trunk/${PLUGIN_ASSETS_DIR}" ]];
+then
+	echo "Checking Plugin icon, banner and screenshots ..."
+	rm -Rf assets/
+	mv trunk/$PLUGIN_ASSETS_DIR assets
+fi
+
 # DELETE VERSION TAG
 rm -Rf tags/${VERSION}
-
-# COPY GIT DIR TO TRUNK
-cp -R "$ROOT_PATH$TEMP_GITHUB_REPO" trunk/
 
 # DO THE ADD ALL NOT KNOWN FILES UNIX COMMAND
 svn add --force * --auto-props --parents --depth infinity -q
@@ -162,7 +178,7 @@ echo "Copying trunk to new tag"
 svn copy trunk tags/${VERSION} || { echo "Unable to create tag."; exit 1; }
 
 # DO SVN COMMIT
-clear
+# clear
 echo "Showing SVN status"
 svn status
 
@@ -174,12 +190,12 @@ echo ""
 # DEPLOY
 echo ""
 echo "Committing to WordPress.org...this may take a while..."
-svn commit -m "Release "${VERSION}", see readme.txt for the changelog." || { echo "Unable to commit."; exit 1; }
+# svn commit -m "Release "${VERSION}", see readme.txt for the changelog." || { echo "Unable to commit."; exit 1; }
 
 # REMOVE THE TEMP DIRS
 echo "CLEANING UP"
-rm -Rf "$ROOT_PATH$TEMP_GITHUB_REPO"
-rm -Rf "$ROOT_PATH$TEMP_SVN_REPO"
+rm -Rf "$TEMP_GITHUB_REPO"
+rm -Rf "$TEMP_SVN_REPO"
 
 # DONE, BYE
 echo "RELEASER DONE :D"
